WINDOW_TITLE = "Maze Explorer"

MAZE_WIDTH = 50
MAZE_HEIGHT = 50
BLOCK_SIZE = 15

GENERATIONS = 100
POPULATION_SIZE = 100
MUTATION_RATE = 0.01

START_COORDS = (1,1)
END_COORDS = (MAZE_HEIGHT-1,MAZE_WIDTH-1)

